
FROM python:3.8-slim

WORKDIR /app

COPY requirements.txt .
COPY upload.py .
COPY movies.csv .

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "upload.py"]

# Serve para o upload.py e para upload2.py, só trocar o arquivo e o copy para o de series.csv
